fastlane_version "1.30.1"

default_platform :ios

platform :ios do
  before_all do
    cert
    sigh(force: true)
    ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]
    gym
  end

  lane :build do
  end

  lane :beta do
    increment_version_number
    pilot(skip_submission: true)
  end

  lane :deploy do
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
